package com.akki.jokeapi.controller;

import java.util.Arrays;
import java.util.List;

public class Jokes {
    List<String> jokes = Arrays.asList
            (
                    "What did one hat say to the other?\nYou wait here — I'll go on ahead!",
                    "Why don't the circus lions eat the clowns?\nBecause they taste funny!",
                    "What did the pirate say when he turned 80?\n\"Aye matey.\"",
                    "Why did the chicken cross the playground?\nTo get to the other slide!",
                    "Why did the actor fall through the floorboards?\nThey were going through a stage!",
                    "Why did a scarecrow win a Nobel prize?\nHe was outstanding in his field!",
                    "Why are peppers the best at archery?\nBecause they habanero!",
                    "What did the duck say after she bought chapstick?\nPut it on my bill!",
                    "Why did an old man fall in a well?\nBecause he couldn\'t see that well!",
                    "What do you call a fake noodle?\nAn impasta!",
                    "What did the three-legged dog say when he walked into a saloon?“I\'m looking for the man who shot my paw!”",
                    "How do you tell the difference between a bull and a cow?\nIt is either one or the udder!",
                    "What\'s red and smells like blue paint?\nRed paint!",
                    "What\'s the difference between a hippo and a Zippo?\nOne is very heavy, the other is a little lighter!",
                    "jokes for kids\nWhat happened when Bluebeard fell overboard in the Red Sea?\nHe got marooned!",
                    "Why couldn\'t the skeleton go to school?\nHis heart just wasn\'t in it.",
                    "What did the termite say when it walked into a bar?\"Where\'s the bar tender?\"",
                    "Why can\'t you send a duck to space?\nBecause the bill would be astronomical!",
                    "What does Jeff Bezos do before he goes to sleep?\nHe puts his PJ-Amazon!",
                    "What happened when the world\'s tongue-twister champion got arrested?\nThey gave him a tough sentence!",
                    "What did the mama cow say to the calf?\nIt\'s pasture bedtime!",
                    "How does a vampire start a letter?\nTomb it may concern!",
                    "What do you call an illegally parked frog?\nToad!",
                    "What did one plate say to the other?\nDinner is on me!",
                    "Why do hummingbirds hum?\nBecause they don\'t know the words!",
                    "What do sprinters eat before a race?\nNothing. They fast!",
                    "Two muffins are baking in an oven. One of them looks to the other and says, \"Phew, it\'s getting hot in here!\" The other looks back and says, \"Ack! A talking muffin!\"",
                    "Animal Jokes for Kids\nbest jokes for kids\nWhat kind of cat likes living in water?\nAn octo-puss.",
                    "Why did the dinosaur cross the road?\nBecause chickens hadn\'t evolved yet.",
                    "What do you call a cow that can\'t make milk?\nAn udder failure — a milk dud.",
                    "What do cats eat for breakfast?\nMice Crispies!",
                    "What do you call an elephant that doesn\'t matter?\nAn irrelephant!",
                    "What do you get when you cross a rabbit with shellfish?\nAn oyster bunny!",
                    "Where do polar bears keep their money?\nIn a snow bank!",
                    "Why did the pony get sent to his room?\nHe wouldn\'t stop horsing around!",
                    "What kind of dog does a magician have?\nA Labracadabrador!",
                    "Where do cows go on Friday nights?\nThey go to the moo-vies!",
                    "Why couldn\'t the pony sing “Happy Birthday?”\nBecause she was just a little hoarse!",
                    "How do you make an octopus laugh?\nWith ten-tickles!",
                    "How do you keep a bull from charging?\nTake away its credit card!",
                    "Why can\'t a leopard hide?\nBecause he\'s always spotted!",
                    "jokes for kids\nHow do you get a squirrel to like you?\nAct like a nut!",
                    "What is the difference between a cat that took a nap on the Xerox machine and a cat that imitates everything you do?\nOne is a cat copy, and the other is a copy cat.",
                    "How do young bees get to school?\nThey take the school buzz!",
                    "What do frogs order at fast-food restaurants?\nFrench flies!",
                    "What do you get from a pampered cow?\nSpoiled milk!",
                    "What do you call an alligator who solves mysteries?\nAn investigator!",
                    "Why is a snake difficult to fool?\nYou can\'t pull its leg!",
                    "What kind of socks do grizzlies wear?\nNone, they have bear feet!",
                    "What do you get when you cross a snail with a porcupine?\nA slowpoke!",
                    "What did the dog say when it sat on sandpaper?\"Ruff!\"",
                    "What\'s a cat\'s favorite dessert?\nChocolate mouse!",
                    "What fish only swims at night?\nStarfish!",
                    "What does a triceratops sit on?\nIts tricera-bottom!",
                    "Knock Knock Jokes for Kids\njokes for kids\nKnock, knock.Who\'s there?\nWeirdo.\nWeirdo who?\nWeirdo you think you\'re going?",
                    "Knock, knock.Who\'s there?\nHowl.\nHowl who?\nHowl you know unless you open the door?",
                    "Knock, knock.Who\'s there?\nVenice.\nVenice who?\nVenice your family coming home?",
                    "Knock, knock.Who\'s there?\nWeekend.\nWeekend who?\nWeekend do anything we want!",
                    "Knock, knock.Who\'s there?\nFigs.\nFigs who?\nFigs the doorbell, I\'ve been knocking forever!",
                    "Knock, knock.Who\'s there?\nTheodore.\nTheodore who?\nTheodore wasn\'t opened so I knocked!",
                    "Knock, knock.Who\'s there?\nTank.\nTank who?\nYou\'re welcome!",
                    "Knock, knock.Who\'s there?\nIsabel.\nIsabel who?\nIsabel not working?",
                    "Knock, knock.Who\'s there?\nIce cream.\nIce cream who?\nICE CREAM SO YOU CAN HEAR ME!",
                    "Knock, knock.Who\'s there?\nIcy.\nIcy who?\nIcy you in there!",
                    "Knock, knock.Who\'s there?\nDozen.\nDozen who?\nDozen anyone want to let me in?",
                    "Knock, knock.Who\'s there?\nScold.\nScold who?\nScold outside, let me in!",
                    "Knock, knock.Who\'s there?\nWater.\nWater who?\nWater you asking so many questions for, just open up!",
                    "Knock, knock.Who\'s there?\nCargo.\nCargo who?\nCar go, “Toot toot, vroom, vroom!”",
                    "50 best jokes for kids\nKnock, knock.\nWho there?\nNoah.\nNoah who?\nKnow a place I can spend the night?",
                    "Knock, knock.Who\'s there?\nOnion.\nOnion who?\nOnion mark, get set, go!",
                    "Knock, knock.Who\'s there?\nCereal.\nCereal who?\nCereal pleasure to be invited over!",
                    "Knock, knock.Who\'s there?\nHatch.\nHatch who?\nBless you!",
                    "Knock, knock.Who\'s there?\nAnnie.\nAnnie who?\nAnnie body home?",
                    "Knock, knock.Who\'s there?\nBoo.\nBoo who?\nDon\'t cry, it\'s just a joke!",
                    "Knock, knock.Who\'s there?\nLettuce.\nLettuce who?\nLettuce in, it\'s cold out here!",
                    "Knock, knock.Who\'s there?\nAn interrupting cow.\nAn interrupt—\nMOO!",
                    "Knock, knock.Who\'s there?\nOwls go.\nOwls go who?\nThat\'s right!",
                    "Knock, knock.Who\'s there?\nA little old lady.\nA little old lady who?\nHey, I didn\'t know you could yodel!",
                    "Knock, knock.Who\'s there?\nNana.\nNana who?\nNana your business!",
                    "Knock, knock.Who\'s there?\nToodle\nToodle who?\nToodle-loo!",
                    "Knock, knock.Who\'s there?\nSpell.\nSpell who?\nOkay, W-H-O!",
                    "Food Jokes for Kids\nbest jokes for kids\nHow does a cucumber become a pickle?\nIt goes through a jarring experience.",
                    "What\'s a turnip\'s favorite soda?\nRoot beer!",
                    "What happened when the cheese shop exploded?\nDa brie was everywhere!",
                    "What\'s a piece of bread\'s least favorite chore?\nDoing a loaf of laundry.",
                    "What did the bunny say to the carrot?\nIt\'s been nice gnawing you!",
                    "What do you call a sad strawberry?\nA blueberry!",
                    "Why did the tomato blush?\nBecause it saw the salad dressing!",
                    "What did the pizza say to the topping?\nI never sau-sage a pretty face!",
                    "Which vegetable do sailors hate the most?\nLeeks!",
                    "What do you call a cheese that\'s not yours?\nNacho cheese!",
                    "Why did the cookie go to the nurse?\nBecause he felt crummy!",
                    "What kind of room doesn\'t have doors?\nA mushroom!",
                    "What kind of key opens a banana?\nA mon-key!",
                    "What happens when a grape gets run over crossing the street?\nA traffic jam!",
                    "jokes for kids\nWhat kind of fruit do scarecrows love the most?\nStraw-berries!",
                    "Why couldn\'t the sesame seed leave the casino?\nBecause it was on a roll",
                    "How do you make an apple turnover?\nPush it down a hill!",
                    "What does garlic do when it gets hot?\nIt takes its cloves off!",
                    "Where does fruit go on vacation?\nPear-is!",
                    "Why did the melons choose not to get married?\nBecause they cantaloupe!",
                    "What does a lemon say when it answers the phone?\nYellow!",
                    "What did one dried fruit say when another asked it to the movies?\nIt\'s a date!",
                    "Why do bees have sticky hair?\nThey use honeycombs!",
                    "What does a cow call an earthquake?\nA milkshake!",
                    "Why did the man go to the yogurt museum?\nTo get a little culture!",
                    "Why couldn\'t the sesame seed climb up the hill?\nBecause it was on a roll!",
                    "Why can\'t you trust tacos?\nBecause they always spill the beans!",
                    "Math Jokes for Kids\nbest jokes for kids\nWhy is the obtuse triangle always frustrated?\nBecause it\'s never right!",
                    "Why do plants hate math?\nBecause it\'s full of square roots!",
                    "What do you call people who really like tractors?\nProtractors!",
                    "How come no one picks statistics as their favorite subject?\nIt\'s just average.",
                    "Why did two 4s skip dinner?\nBecause they already 8!",
                    "Did you hear about the mathematician who\'s afraid of negative numbers?\nHe\'ll stop at nothing to avoid them!",
                    "What did the triangle feel sorry for the circle?\nBecause it\'s pointless!",
                    "Why was the math book sad?\nIt had too many problems!",
                    "Why couldn\'t the angle get a loan?\nBecause his parents wouldn\'t cosine!",
                    "What do you call a number that can\'t stay in one place?\nA roamin\' numeral!",
                    "Why should you never trust someone writing on graph paper?\nBecause they must be plotting something!",
                    "What do you call two guys who love math?\nAlgebros!",
                    "What do you get when you divide a Jack o\' lantern by its diameter?\nPumpkin pi!",
                    "50 best jokes for kids\nWhy was the fraction nervous about marrying the decimal?\nBecause it would have to convert!",
                    "Why was the triangle the MVP of the basketball team?\nIt always made three-pointers!",
                    "What do you call a hen who counts her own eggs?\nA mathema-chicken!",
                    "What did the 90° angle say after an argument?\"It turns out, I was right!\"",
                    "What tool do mathematicians use most?\nMulti-pliers!",
                    "Why did the student get upset when their teacher called them average?\nIt was a mean thing to say!",
                    "If a math teacher had four apples in one hand and five apples in the other hand, what would they have altogether?\nReally big hands!",
                    "What did the 0 say to the 8?\nNice belt!",
                    "Why was 6 afraid of 7?\nBecause 7, 8, 9!",
                    "Why should you never start a conversation with pi?\nIt\'ll just go on forever!",
                    "What is a bird\'s favorite type of math?\nOWL-gebra!",
                    "Why do teenagers travel in groups of threes and fives?\nBecause they can\'t even!",
                    "Did you hear about the the circle that kept going to school?\nIt has 360°!",
                    "Silly Jokes for Kids\nbest jokes for kids\nWhere would you be most likely to find an elephant?\nThe same place you lost one!",
                    "Why did the football coach yell at the vending machine?\nThey wanted their quarter back!",
                    "What do you call a bear without any teeth?\nA gummy bear!",
                    "Why did the robber take a bath before he left the scene of the crime?\nHe wanted to make a clean getaway!",
                    "Why does it take pirates a long time to learn the alphabet?\nBecause they can spend years at C!",
                    "What did one snowman say to the other snowman?\nIt smells like carrots over here!",
                    "What did one wall say to the other wall?\nI\'ll meet you at the corner!",
                    "Why did the kid throw his clock out the window?\nBecause he wanted to see time fly!",
                    "What do you call a huge pile of cats?\nA meow-ntain!",
                    "Why wouldn\'t the shrimp share his treasure?\nBecause he was a little shellfish!",
                    "Why is Cinderella bad at soccer?\nBecause she\'s always running away from the ball!",
                    "What does a rain cloud wear under its clothes?\nThunderwear!",
                    "Why do vampires seem sick all the time?\nBecause they\'re always coffin!",
                    "How do you get an astronaut\'s baby to stop crying?\nYou rocket!",
                    "50 best jokes for kids\nWhat is fast, loud and crunchy?\nA rocket chip!",
                    "What\'s the best thing about Switzerland?\nI don\'t know, but the flag is a big plus!",
                    "Did you hear about the claustrophobic astronaut?\nThey just needed a little space.",
                    "Why are ghosts bad liars?\nBecause you can see right through them!",
                    "Why are spiders so smart?\nThey can find everything on the web!",
                    "What are mummies\' favorite lunches?\nWraps!",
                    "How does Darth Vader like his toast?\nOn the dark side!",
                    "Why are mountains so funny?\nThey\'re just hill areas!",
                    "Why did the student eat his homework?\nBecause his teacher told him it would be a piece of cake!",
                    "What is the Easter bunny\'s favorite type of music?\nHip-hop!",
                    "Why did Beethoven get rid of his chickens?\nAll they ever said was, “Bach, Bach, Bach!”",
                    "Why did the man name his dogs Rolex and Timex?\nBecause they were watchdogs!",
                    "Why is grass so dangerous?\nBecause it\'s full of blades!",
                    "Puns for Kids\n50 best jokes for kids\nWhat did the Dalmatian say after lunch?\nThat hit the spot!",
            "What do you call a bee that can\'t make up its mind?\nA maybe!",
            "What did one volcano say to the other?\nI lava you!",
            "What did the teacher say when a book fell on their head?\nI have only my shelf to blame.",
            "What kind of tree can fit in one hand?\nA palm tree!",
            "How do they keep the basketball arena cool?\nThey fill it with fans!",
            "What does a book do to keep warm in the winter?\nIt puts on a jacket!",
            "What did the lightbulb say to its sweetheart?\nI wuv you a watt!",
            "What did the fisherman say to the magician?\nPick a cod, any cod!",
            "Why did the picture go to prison?\nBecause it was framed!",
            "Why do bicycles fall over?\nBecause they\'re two-tired!",
            "If a seagull flies over the sea, what flies over the bay?\nA bagel!",
            "What does the ocean do when it sees its friends?\nIt waves!",
            "jokes for kids\nWhat do you get when you mix a cocker spaniel, a poodle, and a ghost?\nA cocker-poodle boo!",
            "What is a tornado\'s favorite game to play?\nTwister",
            "How did the students feel when they learned about electricity?\nTotally shocked!",
            "Why did the golfer wear two pairs of pants?\nJust in case he got a hole in one!",
            "Why was the broom late?\nIt over-swept!",
            "What did the paper say to the pencil?\nWrite on!",
            "What do you call a belt made of watches?\nA waist of time!",
            "Where do sailboats go when they\'re sick?\nTo the dock!",
            "How does the moon cut his hair?\nEclipse it!",
            "What do you do when a lemon gets sick?\nYou give it lemon-aid!",
            "What\'s worse than raining cats and dogs?\nHailing taxis!",
            "How can you tell if a tree is a dogwood tree?\nBy its bark!",
            "What do astronauts do before throwing a party?\nThey planet!",
            "Corny Dad Jokes for Kids\njokes for kids\nWhat kind of water can\'t freeze?\nHot water!",
            "Why do we put candles on top of birthday cakes?\nBecause it\'s hard to light them from the bottom!",
            "Why didn\'t the shopper buy the camo pants they wanted?\nThey couldn\'t find any!",
            "What did the family say when they lost 25% of their roof?\nOof.",
            "Why are elevator jokes so good?\nThey work on many levels!",
            "What\'s worse than finding a worm in your apple?\nFinding half a worm in your apple!",
            "What do you call a boomerang that doesn\'t come back?\nA stick!",
            "What do you call a bear with no ears?\nA “B!”",
            "What do pirates pay for corn?\nA buck an ear!",
            "Which hand is it better to write with?\nNeither, it\'s better to write with a pencil!",
            "What do you call a fish with no eye?\nA fsh!",
            "Why are balloons so expensive?\nInflation!",
            "What breed of dog can jump higher than a skyscraper?\nAny breed of dog. Skyscrapers can\'t jump!",
            "Why can\'t you trust atoms?\nThey make up everything!",
            "50 best jokes for kids\nDid you hear about the woman whose left side was cut off?\nShe\'s all right now.",
            "Why did it take so long for a man to eat a clock?\nIt was very time-consuming.",
            "What\'s the one thing will you get every year on your birthday, guaranteed?\nA year older!",
            "Did you hear about the unemployed personal trainer?\nThey gave their too-weak notice!",
            "What\'s brown and sticky?\nA stick!",
            "Why was the calendar afraid?\nIts days were numbered!",
            "What\'s E.T. short for?\nBecause he\'s only got little legs!",
            "Did you hear about the guy who invented the knock-knock joke?\nHe won the \"no-bell\" prize!",
            "Why can\'t a hand be 12 inches long?\nBecause then it would be a foot!",
            "Why is it hard to understand volunteers?\nBecause they make no cents!",
            "How much does it cost Santa to park his sleigh?\nNothing, it\'s on the house!",
            "How is it that I only know 25 letters of the alphabet?\nI just don\'t know y!",
            "When does a regular joke become a dad joke?\nWhen it becomes apparent!",
            "Jokes for Little Kids\n50 best jokes for kids\nWhat has two legs but can\'t walk?\nA pair of pants!",
            "Where do you learn how to make ice cream?\nSundae school!",
            "What do you call a lazy kangaroo?\nA pouch potato!",
            "Where do pencils come from?\nPennsylvania!",
            "What did the cat say when it fell down the stairs?\nMe-ow!",
            "Why can\'t you tell a joke to an egg?\nIt might crack up!",
            "Why are fish so smart?\nBecause they live in schools!",
            "What did the big flower say to the little flower?\nHi, bud!",
            "How can you make a tissue dance?\nPut a little boogie in it!",
            "What did the buffalo say when his little boy left for school?\nBison!",
            "What animal can you always find at a baseball game?\nA bat!",
            "Why did the boy throw a stick of butter out the window?\nBecause he wanted to see a butterfly!",
            "What did Baby Corn say to Mama Corn?\"Where is Pop Corn?\"",
            "What do you call a train with a cold?\nA-choo choo train!",
            "50 best jokes for kids\nWhat do elves learn in school?\nThe elf-abet!",
            "How did the barber win the race?\nThey knew a short cut!",
            "What do you call a pig that does karate?\nA pork chop!",
            "Where do elephants pack their clothes?\nIn their trunks!",
            "What do you call a fly without wings?\nA walk!",
            "What do you call a duck that gets straight-As?\nA wise quacker!",
            "Why do giraffes have such long necks?\nBecause they have smelly feet!",
            "What did the cop say to their tummy?\nYou\'re under a vest!",
            "Why did the teddy bear not ask for dessert?\nBecause he was already so stuffed!",
            "Which bird is always out of breath?\nA puffin!",
            "What\'s a witch\'s favorite school subject?\nSpelling!",
            "How do you talk to a giant?\nUse big words!",
            "Where do sheep go to get their hair cut?\nThe baa-baa shop!",
            "Jokes for Big Kids\n50 best jokes for kids\nWhat did the limestone say to the geologist?\nDon\'t take me for granite!",
            "What did the meteorologist say when they tried to catch fog in their hands?\"I mist.\"",
            "What has four arms, four legs and four eyes?\nFour pirates.",
            "What do you call a dinosaur that wears glasses?\nTyrannosaurus Specs",
            "What do you call a line of rabbits jumping backwards?\nA receding hare-line!",
            "What has four wheels and flies?\nA garbage truck!",
            "What did one eye say to the other eye?\nBetween us, something smells!",
            "What did the sink say to the toilet?\nWow, you look really flushed!",
            "What gets wetter the more that it dries?\nA towel!",
            "What did the traffic light say to the car?\nLook away, I\'m about to change!",
            "What can you catch, but never throw?\nA cold!",
            "What has more letters than the alphabet?\nThe post office!",
            "What\'s black and white and read all over?\nA newspaper!",
            "What\'s black and white and red all over?\nA sunburned zebra!",
            "50 best jokes for kids\nWhat did the snail say when it rode on the turtle\'s back?\nWheeeee!",
            "Did you hear about the kid who drank eight sodas?\nHe burped 7-Up!",
            "Why did the cell phone get glasses?\nBecause it lost all its contacts.",
            "What runs around a baseball field but never moves?\nA fence!",
            "What is brown and hairy and wears sunglasses?\nA coconut on vacation!",
            "What time is it when an elephant sits on your fence?\nTime to get a new fence!",
            "What\'s the difference between boogers and broccoli?\nKids don\'t eat broccoli!",
            "What did the apple say to the worm?\nNothing, apples can\'t talk!",
            "What musical instrument can you find in the bathroom?\nA tuba toothpaste!",
            "What do you call a dinosaur with bad vision?\nA Do-you-think-he-sarus!",
            "What do you get when you cross a centipede with a parrot?\nA walkie talkie!",
            "Which dinosaur has the best vocabulary?\nThe thesaurus!",
            "What do you call two bananas?\nA pair of slippers!"
            );
}
